name: Deploy Flask App

on:
  push:
    branches:
      - main  # Adjust as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flask app
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          REPLIKA_EMAIL: ${{ secrets.REPLIKA_EMAIL }}
          REPLIKA_PASSWORD: ${{ secrets.REPLIKA_PASSWORD }}
        run: |
          python app.py & docker run -it -e NGROK_AUTHTOKEN=2IfWZ6EdjqQojALawNDc7DRjmD9_6kWdcpDLX3MfYRLVehnik ngrok/ngrok http 80 --domain=wanted-tolerant-toucan.ngrok-free.app  # Start your Flask app
